# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55797bc3fb751445027743d4a70fdfbe"
application_url = "https://linking-basic-awards-secretary.trycloudflare.com"
embedded = true
name = "projectauth4"
handle = "projectauth4"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://linking-basic-awards-secretary.trycloudflare.com/auth/callback",
  "https://linking-basic-awards-secretary.trycloudflare.com/auth/shopify/callback",
  "https://linking-basic-awards-secretary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "classification-prompt-3.myshopify.com"
automatically_update_urls_on_dev = true
